config/routes.rb
Rails.application.routes.draw do
  resources :owls
  resources :hedgehogs
  resources :chicks
  resources :dogs
  resources :cats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: redirect("/cats")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
class Cat < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  
  def self.ransackable_attributes(auth_object = nil)
    %w[age created_at id id_value name updated_at]
  end
end

app/models/chick.rb
class Chick < ApplicationRecord
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/models/hedgehog.rb
class Hedgehog < ApplicationRecord
end

app/models/owl.rb
class Owl < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: %i[ show edit update destroy ]

  # GET /cats
  def index
    @search = Cat.ransack(params[:q])
    @search.sorts = 'id desc' if @search.sorts.empty?
    @cats = @search.result.page(params[:page])
  end

  # GET /cats/1
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      flash.now[:notice] = "ねこ を登録しました。"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cats/1
  def update
    if @cat.update(cat_params)
      flash.now[:notice] = "ねこ を更新しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /cats/1
  def destroy
    @cat.destroy!
    flash.now[:notice] = "ねこ を削除しました。"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_params
      params.require(:cat).permit(:name, :age)
    end
end

app/controllers/chicks_controller.rb
class ChicksController < ApplicationController
  before_action :set_chick, only: %i[ show edit update destroy ]

  # GET /chicks
  def index
    @chicks = Chick.all
  end

  # GET /chicks/1
  def show
  end

  # GET /chicks/new
  def new
    @chick = Chick.new
  end

  # GET /chicks/1/edit
  def edit
  end

  # POST /chicks
  def create
    @chick = Chick.new(chick_params)

    if @chick.save
      redirect_to @chick, notice: "Chick was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /chicks/1
  def update
    if @chick.update(chick_params)
      redirect_to @chick, notice: "Chick was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /chicks/1
  def destroy
    @chick.destroy!
    redirect_to chicks_url, notice: "Chick was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chick
      @chick = Chick.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chick_params
      params.require(:chick).permit(:name, :age)
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: %i[ show edit update destroy ]

  # GET /dogs
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  def create
    @dog = Dog.new(dog_params)

    if @dog.save
      redirect_to @dog, notice: "Dog was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /dogs/1
  def update
    if @dog.update(dog_params)
      redirect_to @dog, notice: "Dog was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /dogs/1
  def destroy
    @dog.destroy!
    redirect_to dogs_url, notice: "Dog was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dog_params
      params.require(:dog).permit(:name, :age)
    end
end

app/controllers/hedgehogs_controller.rb
class HedgehogsController < ApplicationController
  before_action :set_hedgehog, only: %i[ show edit update destroy ]

  # GET /hedgehogs
  def index
    @hedgehogs = Hedgehog.all
  end

  # GET /hedgehogs/1
  def show
  end

  # GET /hedgehogs/new
  def new
    @hedgehog = Hedgehog.new
  end

  # GET /hedgehogs/1/edit
  def edit
  end

  # POST /hedgehogs
  def create
    @hedgehog = Hedgehog.new(hedgehog_params)

    if @hedgehog.save
      redirect_to @hedgehog, notice: "Hedgehog was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /hedgehogs/1
  def update
    if @hedgehog.update(hedgehog_params)
      redirect_to @hedgehog, notice: "Hedgehog was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /hedgehogs/1
  def destroy
    @hedgehog.destroy!
    redirect_to hedgehogs_url, notice: "Hedgehog was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hedgehog
      @hedgehog = Hedgehog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hedgehog_params
      params.require(:hedgehog).permit(:name, :age)
    end
end

app/controllers/owls_controller.rb
class OwlsController < ApplicationController
  before_action :set_owl, only: %i[ show edit update destroy ]

  # GET /owls
  def index
    @owls = Owl.all
  end

  # GET /owls/1
  def show
  end

  # GET /owls/new
  def new
    @owl = Owl.new
  end

  # GET /owls/1/edit
  def edit
  end

  # POST /owls
  def create
    @owl = Owl.new(owl_params)

    if @owl.save
      redirect_to @owl, notice: "Owl was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /owls/1
  def update
    if @owl.update(owl_params)
      redirect_to @owl, notice: "Owl was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /owls/1
  def destroy
    @owl.destroy!
    redirect_to owls_url, notice: "Owl was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owl
      @owl = Owl.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def owl_params
      params.require(:owl).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sidebar_link_to(path, emoji, text)
    classes = %w[my-1 nav-link text-white]
    classes << "active" if current_page?(path)
    
    link_to(path, class: classes) do
      tag.span(class: "me-2") { emoji } + tag.span { text }
    end
  end
  
  def icon(icon_name)
    tag.i(class: ["bi", "bi-#{icon_name}"])
  end
  
  def icon_with_text(icon_name, text)
    tag.span(icon(icon_name), class: "me-2") + tag.span(text)
  end
  
  def turbo_stream_flash
    turbo_stream.update "flash", partial: "flash"
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/chicks_helper.rb
module ChicksHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/hedgehogs_helper.rb
module HedgehogsHelper
end

app/helpers/owls_helper.rb
module OwlsHelper
end

app/views/application/_flash.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <%= alert %>
  </div>
<% end %>

app/views/application/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 py-3 px-3 bg-dark text-white vh-100">
  <div class="d-flex align-items-center justify-content-center py-2">
    <%= link_to "AMS", root_path, class: "text-white display-6 text-decoration-none" %>
  </div>
  <hr />

  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= sidebar_link_to(cats_path, "🐱", "ねこ") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(dogs_path, "🐶", "いぬ") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(chicks_path, "🐣", "ひよこ") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(hedgehogs_path, "🦔", "ハリネズミ") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(owls_path, "🦉", "フクロウ") %>
    </li>
  </ul>
</div>

app/views/cats/_cat.html.erb
<%= turbo_frame_tag cat do %>
  <div class="row py-2 border-top">
    <div class="col-4 my-auto">
      <%= cat.name %>
    </div>
    <div class="col-4 my-auto">
      <%= cat.age %>
    </div>
    <div class="col-4">
      <div class="d-flex justify-content-end">
        <%= link_to "編集", edit_cat_path(cat), class: "btn btn-sm btn-outline-primary me-2" %>
        <%= link_to "削除", cat, class: "btn btn-sm btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %>
      </div>
    </div>
  </div>
<% end %>

app/views/cats/_form.html.erb
<%= turbo_frame_tag cat do %>
  <%= bootstrap_form_with(model: cat) do |form| %>

    <%= form.text_field :name, required: false %>
    <%= form.number_field :age, required: false %>

    <%= form.primary %>
    <%= link_to "キャンセル", cats_path, class: "btn btn-sm btn-outline-secondary" %>
  <% end %>
<% end %>

app/views/cats/create.turbo_stream.erb
<%= turbo_stream.prepend "cats", @cat %>

<%= turbo_stream.update Cat.new, "" %>
<%= turbo_stream_flash %>

app/views/cats/destroy.turbo_stream.erb
<%= turbo_stream.remove @cat %>
<%= turbo_stream_flash %>

app/views/cats/edit.html.erb
<h1>ねこ を編集する</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "詳細", @cat %> |
  <%= link_to "戻る", cats_path %>
</div>

app/views/cats/index.html.erb
<!-- 見出し -->
<h4 class="fw-bold">
  <span class="me-1">🐱</span>
  <span>ねこ</span>
</h4>

<!-- 検索フォーム -->
<div class="card shadow mt-3">
  <div class="card-header">
    <%= icon_with_text("search", "検索条件") %>
  </div>

  <div class="card-body">
    <%= search_form_for(
      @search,
      html: {
        data: {
          turbo_frame: "cats-list",
          controller: "form",
          action: "input->form#submit"
        }
      }) do |f| %>

      <div class="row g3 mb-3">
        <div class="col-4 col-xl-2">
          <%= f.label :name_cont, "名前", class: "form-label" %>
          <%= f.search_field :name_cont, class: "form-control" %>
        </div>
        <div class="col-4 col-xl-2">
          <%= f.label :age_eq, "年齢", class: "form-label" %>
          <%= f.search_field :age_eq, class: "form-control" %>
        </div>
        <div class="col-4 d-flex align-items-end">
          <%= link_to "リセット", cats_path, class: "btn btn-outline-secondary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- 一覧 -->
<div class="card shadow mt-3">
  <div class="card-header">
    <%= icon_with_text("table", "一覧") %>
  </div>

  <div class="card-body mx-3">
    <%= turbo_frame_tag "cats-list" do %>
      <div class="row py-2">
        <div class="col-4 mt-auto">
          <%= sort_link(@search, :name) %>
        </div>
        <div class="col-4 mt-auto">
          <%= sort_link(@search, :age) %>
        </div>
        <div class="col-4 d-flex justify-content-end">
          <%= link_to icon_with_text("plus-circle", "登録"),
                      new_cat_path,
                      class: "btn btn-outline-primary",
                      data: { turbo_frame: dom_id(Cat.new) }
          %>
        </div>
      </div>

      <%= turbo_frame_tag Cat.new %>
      <div id="cats">
        <%= render @cats %>
      </div>

      <div class="d-flex justify-content-end mt-3">
        <%= paginate @cats %>
      </div>
    <% end %>
  </div>
</div>

app/views/cats/new.html.erb
<h1>ねこ を登録する</h1>

<%= render "form", cat: @cat %>

<br>

<div>
  <%= link_to "戻る", cats_path %>
</div>

app/views/cats/show.html.erb
<div id="<%= dom_id @cat %>">
  <p>
    <strong>名前:</strong>
    <%= @cat.name %>
  </p>

  <p>
    <strong>年齢:</strong>
    <%= @cat.age %>
  </p>
</div>

<div>
  <%= link_to "編集", edit_cat_path(@cat) %> |
  <%= link_to "戻る", cats_path %>

  <%= button_to "削除", @cat, method: :delete %>
</div>

app/views/cats/update.turbo_stream.erb
<%= turbo_stream.replace @cat %>
<%= turbo_stream_flash %>

app/views/chicks/_chick.html.erb
<div id="<%= dom_id chick %>">
  <p>
    <strong>Name:</strong>
    <%= chick.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= chick.age %>
  </p>

</div>

app/views/chicks/_form.html.erb
<%= form_with(model: chick) do |form| %>
  <% if chick.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chick.errors.count, "error") %> prohibited this chick from being saved:</h2>

      <ul>
        <% chick.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chicks/edit.html.erb
<h1>Editing chick</h1>

<%= render "form", chick: @chick %>

<br>

<div>
  <%= link_to "Show this chick", @chick %> |
  <%= link_to "Back to chicks", chicks_path %>
</div>

app/views/chicks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Chicks</h1>

<div id="chicks">
  <% @chicks.each do |chick| %>
    <%= render chick %>
    <p>
      <%= link_to "Show this chick", chick %>
    </p>
  <% end %>
</div>

<%= link_to "New chick", new_chick_path %>

app/views/chicks/new.html.erb
<h1>New chick</h1>

<%= render "form", chick: @chick %>

<br>

<div>
  <%= link_to "Back to chicks", chicks_path %>
</div>

app/views/chicks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chick %>

<div>
  <%= link_to "Edit this chick", edit_chick_path(@chick) %> |
  <%= link_to "Back to chicks", chicks_path %>

  <%= button_to "Destroy this chick", @chick, method: :delete %>
</div>

app/views/dogs/_dog.html.erb
<div id="<%= dom_id dog %>">
  <p>
    <strong>Name:</strong>
    <%= dog.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= dog.age %>
  </p>

</div>

app/views/dogs/_form.html.erb
<%= form_with(model: dog) do |form| %>
  <% if dog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
        <% dog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render "form", dog: @dog %>

<br>

<div>
  <%= link_to "Show this dog", @dog %> |
  <%= link_to "Back to dogs", dogs_path %>
</div>

app/views/dogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dogs</h1>

<div id="dogs">
  <% @dogs.each do |dog| %>
    <%= render dog %>
    <p>
      <%= link_to "Show this dog", dog %>
    </p>
  <% end %>
</div>

<%= link_to "New dog", new_dog_path %>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render "form", dog: @dog %>

<br>

<div>
  <%= link_to "Back to dogs", dogs_path %>
</div>

app/views/dogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dog %>

<div>
  <%= link_to "Edit this dog", edit_dog_path(@dog) %> |
  <%= link_to "Back to dogs", dogs_path %>

  <%= button_to "Destroy this dog", @dog, method: :delete %>
</div>

app/views/hedgehogs/_form.html.erb
<%= form_with(model: hedgehog) do |form| %>
  <% if hedgehog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hedgehog.errors.count, "error") %> prohibited this hedgehog from being saved:</h2>

      <ul>
        <% hedgehog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hedgehogs/_hedgehog.html.erb
<div id="<%= dom_id hedgehog %>">
  <p>
    <strong>Name:</strong>
    <%= hedgehog.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= hedgehog.age %>
  </p>

</div>

app/views/hedgehogs/edit.html.erb
<h1>Editing hedgehog</h1>

<%= render "form", hedgehog: @hedgehog %>

<br>

<div>
  <%= link_to "Show this hedgehog", @hedgehog %> |
  <%= link_to "Back to hedgehogs", hedgehogs_path %>
</div>

app/views/hedgehogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hedgehogs</h1>

<div id="hedgehogs">
  <% @hedgehogs.each do |hedgehog| %>
    <%= render hedgehog %>
    <p>
      <%= link_to "Show this hedgehog", hedgehog %>
    </p>
  <% end %>
</div>

<%= link_to "New hedgehog", new_hedgehog_path %>

app/views/hedgehogs/new.html.erb
<h1>New hedgehog</h1>

<%= render "form", hedgehog: @hedgehog %>

<br>

<div>
  <%= link_to "Back to hedgehogs", hedgehogs_path %>
</div>

app/views/hedgehogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hedgehog %>

<div>
  <%= link_to "Edit this hedgehog", edit_hedgehog_path(@hedgehog) %> |
  <%= link_to "Back to hedgehogs", hedgehogs_path %>

  <%= button_to "Destroy this hedgehog", @hedgehog, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySandbox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="vh-100">
      <div class="container-fluid">
        <div class="row">

          <div class="ps-0" style="width: 200px;"></div>
          <div class="ps-0 position-fixed" style="width: 200px;">
            <%= render "sidebar" %>
          </div>

          <div class="col my-4">
            <div id="flash">
              <%= render "flash" %>
            </div>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/owls/_form.html.erb
<%= form_with(model: owl) do |form| %>
  <% if owl.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(owl.errors.count, "error") %> prohibited this owl from being saved:</h2>

      <ul>
        <% owl.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/owls/_owl.html.erb
<div id="<%= dom_id owl %>">
  <p>
    <strong>Name:</strong>
    <%= owl.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= owl.age %>
  </p>

</div>

app/views/owls/edit.html.erb
<h1>Editing owl</h1>

<%= render "form", owl: @owl %>

<br>

<div>
  <%= link_to "Show this owl", @owl %> |
  <%= link_to "Back to owls", owls_path %>
</div>

app/views/owls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Owls</h1>

<div id="owls">
  <% @owls.each do |owl| %>
    <%= render owl %>
    <p>
      <%= link_to "Show this owl", owl %>
    </p>
  <% end %>
</div>

<%= link_to "New owl", new_owl_path %>

app/views/owls/new.html.erb
<h1>New owl</h1>

<%= render "form", owl: @owl %>

<br>

<div>
  <%= link_to "Back to owls", owls_path %>
</div>

app/views/owls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @owl %>

<div>
  <%= link_to "Edit this owl", edit_owl_path(@owl) %> |
  <%= link_to "Back to owls", owls_path %>

  <%= button_to "Destroy this owl", @owl, method: :delete %>
</div>